version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eclat_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - eclat_network
    depends_on:
      - db
  db:
    container_name: mariadb
    restart: unless-stopped
    image: mariadb:10.4.33
    environment:
      MARIADB_ROOT_PASSWORD: Cpu25
      #MARIADB_USER: dbuser
      #MARIADB_PASSWORD: strongpw
      MARIADB_DATABASE: eclat_app
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    ports:
     - 3306
    networks:
      - eclat_network

volumes:
  mariadb-data:
    driver: local

networks:
  eclat_network:
    driver: bridge